apiVersion: v1
kind: Service
metadata:
  name: angular-test-backend
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: angular-test
  type: ClusterIP